name: Develop

on:
  push:
    branches:
      - dev
      - develop
    paths:
      - "**/*.py"
      - ".github/workflows/develop.yml"
  pull_request:
    branches:
      - dev
      - develop
    paths:
      - "**/*.py"
      - ".github/workflows/develop.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Set env
        env:
          DEBIAN_FRONTEND: 'noninteractive'

      - name: Install build deps
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
              apt-transport-https \
              build-essential \
              ca-certificates \
              cmake \
              git-flow \
              gpg \
              libboost-all-dev \
              python3-dev \
              unzip \
              wget

      - name: Added CryptoPro repo
        run: |
          echo "machine cryptopro.ru login ${{ secrets.CRYPTOPRO_USERNAME}} password ${{ secrets.CRYPTOPRO_PASSWORD }}" > /etc/apt/auth.conf.d/cryptopro.conf
          chmod 600 /etc/apt/auth.conf.d/cryptopro.conf
          echo "deb https://cryptopro.ru/repo/deb 5.0-unstable main" > /etc/apt/sources.list.d/cprocsp.list
          wget -qO - https://www.cryptopro.ru/sites/default/files/products/csp/cryptopro_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/cryptopro.gpg

      - name: Install CryptoPro and Rutoken driver
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
              cprocsp-pki-cades \
              lsb-cprocsp-devel
          rm /etc/apt/auth.conf.d/cryptopro.conf

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install nox
        uses: excitedleigh/setup-nox@v2.0.0

      - run: nox
